# Generated by Django 5.0.3 on 2024-03-22 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "scores",
            "0002_team_index_alter_position_dx_px_alter_position_dy_px_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="score",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="position",
                to="scores.score",
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="team",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="score",
                to="scores.team",
            ),
        ),
    ]
